### ISSUE TITLE
FYI: CLI interface published for decomment

### ISSUE THREAD

**Issue by jeremyckahn** [vitaly-t/decomment#13]
Hi @vitaly-t, just letting you know that I created a CLI interface for this awesome project: https://www.npmjs.com/package/decomment-cli

Feel free to link it up in the documentation somewhere, or close this issue if you would prefer not to!

**Comment by vitaly-t** [comment]
Very well. Did you know there also was [gulp-decomment] and [grunt-decomment]? :wink:

Does your utility support all the options that `decomment` support? I didn't see how.

By the way, you might want to fix the GitHub link in your package.js file :wink:

[gulp-decomment]:https://github.com/vitaly-t/gulp-decomment
[grunt-decomment]:https://github.com/vitaly-t/grunt-decomment

**Comment by jeremyckahn** [comment]
Ah!  Thanks for the tip; I just fixed my `package.json`.  Your other decomment tools look handy!  I just needed something I could use directly from the command line.  Thanks again for the great project!
