### ISSUE TITLE
UglifyJs error on build

### ISSUE THREAD

**Issue by smellai** [vitaly-t/decomment#19]
I'm trying to use the package in a client applications, everything works smoothly when I run the application locally, but the build breaks:

```
ERROR in app.js from UglifyJs
Unexpected token: name (idx) [app.js:7089,8]

ERROR in app.js from UglifyJs
Unexpected token: name (idx)
```

Any idea?

**Comment by vitaly-t** [comment]
Sorry for responding so late. This library was developed primarily for the server-side. I'm not even sure if it can work on the client side.

Did you make any progress investigating the issue further?

**Comment by smellai** [comment]
No, no progress sorry

**Comment by vitaly-t** [comment]
The error looks like it came from the Uglify library, not from this library.

**Comment by vitaly-t** [comment]
This really looks unrelated. I'm closing it therefore.
