### ISSUE TITLE
trim supports deleting the blank characters before and after the comment

### ISSUE THREAD

**Issue by wll8** [vitaly-t/decomment#21]
# trim supports deleting the blank characters before and after the comment
Supported options:
- trim: false // No processing
- trim: true // all
- trim: `left`,
- trim: `right`,

## Source code:
``` js
const api = new CustomApi({
   axiosConfig: {
     timeout: 10000, // timeouttimeout
     baseURL: config.baseApi,
   },
})
```

## Configuration:
``` js
outStr = decomment(str, {
   trim: true,
});
```

## Actual:
Note: `timeout: 10000,` there is a space after it
``` js
const api = new CustomApi({
  axiosConfig: {
    timeout: 10000, 
    baseURL: config.baseApi,
  },
})
```

## expect:
Note: `timeout: 10000,` there is no space after

``` js
const api = new CustomApi({
   axiosConfig: {
     timeout: 10000,
     baseURL: config.baseApi,
   },
})
```

**Comment by vitaly-t** [comment]
Documentation tells you - `remove empty lines that follow removed full-line comments`. It is not relevant to space characters on the same line, only to extraneous lines that follow a comment line.
