### ISSUE TITLE
Does it support custom annotations?

### ISSUE THREAD

**Issue by wll8** [vitaly-t/decomment#23]
Does it support custom annotations?

I did not find this feature in the documentation, d.ts and issues.

E.g:

``` js
// bash
options.comment = [
   [`#`],
]
```
``` js
// aardio
options.comment = [
   [`//`], 
   [`/*`, `*/`],
]
```

**Comment by vitaly-t** [comment]
It supports all JavaScript-syntax annotations. Are you asking because you haven't tried?

**Comment by wll8** [comment]
Thank you for reading this question carefully.
