### ISSUE TITLE
decomment had an error handling pure css code

### ISSUE THREAD

**Issue by ctrlkk** [vitaly-t/decomment#25]
I love you, but decomment has problems handling pure css code, i.e., css code that is not wrapped in the style tag.

For example:
```JavaScript
const decomment = require('decomment');
decomment(`
.page {
	width: 100%;
	min-height: 100vh;
	background-color: $uni-bg-color-grey;
}

.flex-center {
	display: flex;
	justify-content: center;
	align-items: center;
}
`);
```

**Comment by vitaly-t** [comment]
The main page explains it, you need to use `decomment.text` method for CSS, to process it as plain text.

**Comment by vitaly-t** [comment]
Closing, due to non-response (I don't feel love at all).
