### ISSUE TITLE
Shouldn't assume files use OS line endings

### ISSUE THREAD

**Issue by itslenny** [vitaly-t/decomment#4]
Currently the library is using os.EOL to determine the line endings, but it is common (especially on windows) to run file operations on files that use unix line endings.

I discovered this by using gulp-decomment on a file with unix style line endings on windows. The result was a completely blank file.

Maybe use a line ending regex and the exec function?

```
var EOLRegExp = /\r\n|\n|\r/gm;
var lbFind = EOLRegExp.exec(code);
```

This would allow support for mixed line endings and be OS independent.

**Comment by vitaly-t** [comment]
I don't see how trying to process lines on an OS for files with the wrong decoding could ever work. You cannot make an assumption where it is the correct/complete line or not, especially when it comes to trimming lines, which the library does (option `trim`).

The OS-dependent way is the only one that's consistent. You need to either fix the files encoding, or not use this type of processing.

I don't know what type of IDE you are using, but for example in WebStorm it changes the line ends automatically.

**Comment by vitaly-t** [comment]
The only way one could improve this library is to add support for overriding line ends, which would work in your case, but would need to be used with care.

**Comment by vitaly-t** [comment]
Option [platform](https://github.com/vitaly-t/decomment#optionsplatform--string) has been added in version 0.8, which allows for any kind of scenario regarding the line breaks.

**Comment by itslenny** [comment]
This is a bad assumption. line endings do not relate to the platform the code is being run on they relate to the platform on which the file was saved (maybe). Really the code should be agnostic to line endings which is what my pull request accomplished, but with your latest update it doesn't work because of the new tests you added that have hard coded line endings.

**Comment by itslenny** [comment]
If you roll back your latest change I will submit the this pull request again... you can review it here before you make a decision. I added one test which fails without my addition and passes with my modifications to the parse.js file.

https://github.com/itslenny/decomment/tree/SupportMixedLineEndings

**Comment by vitaly-t** [comment]
This is testing the mode that you would be using:
```js
describe("auto", function () {
        it("must always ignore solo \\r symbols", function () {
            expect(decomment("//comment\r\rtext", {trim: true, platform: 'auto'})).toBe("");
            expect(decomment("/*comment*/\r\rtext", {trim: true, platform: 'auto'})).toBe("\r\rtext");
        });
        it("must determine Unix and break on \\n", function () {
            expect(decomment("//comment\n\ntext", {trim: true, platform: 'auto'})).toBe("text");
            expect(decomment("/*comment*/\n\ntext", {trim: true, platform: 'auto'})).toBe("text");
        });
        it("must determine Windows and break on \\r\\n", function () {
            expect(decomment("//comment\r\n\r\ntext", {trim: true, platform: 'auto'})).toBe("text");
            expect(decomment("/*comment*/\r\n\r\ntext", {trim: true, platform: 'auto'})).toBe("text");
        });
    });
```
And it is agnostic. When you are saying that it doesn't work - is that the result of your testing or an assumption?

**Comment by itslenny** [comment]
You're right. This works.

It's not nearly as flexible as my proposed solution, and it would still choke on a file with inconsistent line endings (although that is certainly an edge case).

**Comment by vitaly-t** [comment]
I understand you are talking about a hypothetical broken file that uses neither Unix no Windows line endings, rather a mix. But what are the chances of encountering such a file, plus it would already have all the problems on its own, perhaps this library should be used as a tool for resolving such issues.

**Comment by vitaly-t** [comment]
@itslenny I think this concludes it.

Thank you for bringing this up, the library is now much more flexible.

:+1:
