### ISSUE TITLE
breaking changes

### ISSUE THREAD

**Issue by RnbWd** [vitaly-t/decomment#7]
removing `platform` is a breaking change which corresponds to x.0.0 - it was never documented in the strip-comments plugins so I only modified it minor 0.x.0 assuming nobody noticed but regardless of that library which is technically 3rd party and not part of the 'decomment' ecosystem - maintaining the semver protocol is important for the npm ecosystem in general - because inconsistencies (which are very common) prevent libraries from being able to interact seamlessly with the greater ecosystem. It's the reason node.js jumped from 0.12 to 4.2 - there was a huge discussion behind the scenes regarding the adherence to semver - and it's completely dependent on library authors to actually use it - (like the honor system). Ultimately you can version your library any way you want - but as the user base grows - semver becomes more important - and there's thousands of people downloading a plugin that would break because it's based on this library. It's a trivial thing - but it messes with how npm resolves dependencies.

**Comment by RnbWd** [comment]
actually i coded the update wrong - mixed up options with methods - nm I don't forget it

**Comment by vitaly-t** [comment]
The option I removed, i'm sure either nobody used or used it with value `auto`, which is what it became now. One of the reasons I removed it - it is very often people encode a file on one platform, and then try to decomment it on another platform, which results in issues, unless the `auto` mode was used.

Practice showed it was a bad idea, not to have `auto` as the default, which is now corrected.

So, it is not really a breaking change.

**Comment by RnbWd** [comment]
yeah i mixed up the methods with options so you're correct it wasn't really a breaking change - I accidentally wrote each option as a method when I updated it a few days ago - it shouldn't have had an impact on anybody using the library normally and it wasn't documented
